### PR TITLE
Added Limitations to ReadMe

### PR DESCRIPTION
**Pull request by JFolberth**
Provided Limitations on the ReadMe as this is currently not clear in the documentation.

### CODE REVIEW

**Review by sukhans — CHANGES_REQUESTED** [review]
We do support Linux agents, however it is in preview and has limitations / bugs.

I would edit the Limitation to -
Linux support is in Preview and has limitations. Please use Windows agents for full feature set.

**Comment by JFolberth** [comment]
@sukhans I think to accept this edit those limitations should be identified so users know if they run into a new bug/limitation or something that has been documented. Plus allow them to accept the known limitations vs discover on their own.

**Comment by sukhans** [comment]
> @sukhans I think to accept this edit those limitations should be identified so users know if they run into a new bug/limitation or something that has been documented. Plus allow them to accept the known limitations vs discover on their own.

That's a fair ask. @davidknise can we publish a generic list of Linux related bugs/issues that we have open w.r.t. MSDO?
I know we have a list published internally. We could probably sanitize that.

**Comment by JFolberth** [comment]
@davidknise  just bumping this.

**Comment by JFolberth** [comment]
@davidknise @sukhans   bumping this as customer was asking in regards to known limitations.

**Comment by tonybaloney** [comment]
I've just spent 2 hours trying to get the pipeline working only to discover that linux agents don't work. Please can you merge this. The issue backlog is full of similar reports

**Comment by sukhans** [comment]
@JFolberth we made the fixes and this should be fixed now. Linux should work with the tools.

**Pull request closed without merging**
