### PR TITLE
Release v1.7.0

### PR DESCRIPTION
**Pull request by davidknise**
Node16 launchers
Automatic rollbacks in builds

### CODE REVIEW

**Comment by JanneRantala** [comment]
Hi @davidknise! Does this fix issue in Azure pipelines when organisation has disabled Node 6 tasks? Running current version of MicrosoftSecurityDevOps ends with this error 

"The pipeline is not valid. Job Job: Step 'MicrosoftSecurityDevOps' references task 'MicrosoftSecurityDevOps' at version '1.6.0' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator."

**Review by boAndron — APPROVED** [review]

**Comment by dotpaul** [comment]
@JanneRantala I suspect it will as newer ADO libraries are used

**Review by dotpaul — APPROVED** [review]
:shipit:

**Comment by davidknise** [comment]
@JanneRantala yes it should, as it's adding the node16 handler. Please let me know if you continue to see it after today's release.

**Comment by JanneRantala** [comment]
@davidknise @dotpaul  still getting the same error with version 1.7.1

The pipeline is not valid. Job Job: Step 'MicrosoftSecurityDevOps' references task 'MicrosoftSecurityDevOps' at version '1.7.1' contains an execution handler that relies on NodeJS version '6' which is restricted by your administrator.

**Pull request merged**
